apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: test
namespace: default
nameSuffix: -test
images:
- name: obviusowl/roundcube
  newName: reg.lan.terhaak.de/jojo/roundcube
  newTag: 1.4.11-20210216-1
resources:
- roundcube.yaml
- storage.yaml

