{{- if .Values.persistence.existingClaim | not -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: '{{ include "roundcube.fullname" . }}-data'
  labels:
    app: {{ include "roundcube.name" . }}
    chart: {{ include "roundcube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
